spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
    import:
      - application-mall-core-local.yml
aws:
  paramstore:
    enabled: false
cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
      static: ap-northeast-2
    stack:
      auto: false
logging:
  level:
    # Set environment together: AWS_EC2_METADATA_DISABLED=true
    # ref: https://lannstark.tistory.com/71
    com.amazonaws.util.EC2MetadataUtils: error
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - 'aws-parameterstore:'
      - application-mall-core-dev.yml
    name: mall
#aws:
#  paramstore:
#    enabled: true
#    prefix: /config
#    profile-separator: _
#    name: mall
#    region: ap-northeast-2
#    default-context:
#

