spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
    import:
      - application-mall-core-local.yml
aws:
  paramstore:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - 'aws-parameterstore:'
      - application-mall-core-dev.yml
    name: mall
#aws:
#  paramstore:
#    enabled: true
#    prefix: /config
#    profile-separator: _
#    name: mall
#    region: ap-northeast-2
#    default-context:
#

