spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/mall
  jpa:
    hibernate:
      ddl-auto: update
    #      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
