spring:
  config:
    activate:
      on-profile: dev
    import:
      - 'aws-parameterstore:'
  jpa:
    hibernate:
      ddl-auto: update
    #      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  datasource:
    username: ${jdbc.username}
    password: ${jdbc.password}
    url: ${jdbc.url}
aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: mall
cloud:
  aws:
    credentials:
