FROM java:11

ENV BASE_PORT = 8081

RUN sudo fuser -k $BASE_PORT/tcp

ENV STDOUT=/home/ec2-user/stdout.log
ENV STDERR=/home/ec2-user/stderr.log
ENV BASE_PATH = /home/ec2-user
ENV HEALTH_CHECK_URL = http://loocalhost:$BASE_PORT/actuator/health






