spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local

test: aaa

---
spring:
  config:
    activate:
      on-profile: dev
    import: 'aws-parameterstore:'
test: ${test}
aws:
  paramstore:
    enabled: true
    prefix: config
    profile-separator: _
    name: eureka
    region: ap-northeast-2

