version: 0.0
os: linux
files:
  - source: /
    destination: /home/centos

permissions:
  - object: /home/centos/
    pattern: "**"
    owner: centos
    group: centos
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/afterInstall.sh
      timeout: 30

  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 60

