FROM amazoncorretto:11
#
## cloudwatch agent install
#FROM amazonlinux:2.0.20190508
#RUN yum -y install https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
#COPY agent_config.json  /opt/aws/amazon-cloudwatch-agent/bin/agent_config.json
#ENTRYPOINT ["/opt/aws/amazon-cloudwatch-agent/bin/start-amazon-cloudwatch-agent"]
#CMD sleep 10
#


ENV BASE_PORT 8080
ENV STDOUT /home/ec2-user/stdout.log
ENV STDERR /home/ec2-user/stderr.log
ENV BASE_PATH /home/ec2-user
ENV CURRENT_DEPLOY_JAR deploy.jar
COPY /deploy.jar /deploy.jar

CMD sudo nohup java -jar -Dspring.profiles.active=dev ./deploy.jar 1>> $STDOUT 2>> $STDERR &
CMD sleep 120
CMD exit 0
