spring:
  config:
    import: application-auth-core-local.yml
  cloud:
    gateway:
      default-filters:
        - AuthFilterFactory
token:
  access-token-secret: awey34634561235GWSDGVdsgvdsfhyfasdzehgysurhrt232t6347yetseryesrytasrgdasdrgvbasdfgbaedsfrghaewrgaewrghaerghaerha34qw67yy45
  refresh-token-expired: 1209600
  access-token-expired: 1209600
