spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    #      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
pay:
  iamport:
    rest-key: 5561921923220946
    rest-secret: f91239836f18f3704ca8adff9cf62de072e2c09981c1b26adb3a19697071cb75d2b21e7be5d853fb