spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    username: root
    password: admin
    url: r2dbc:mariadb://127.0.0.1:3307/auth
    pool:
      max-size: 100
    initialization-mode: always
logging:
  level:
    # Set environment together: AWS_EC2_METADATA_DISABLED=true
    # ref: https://lannstark.tistory.com/71
    com.amazonaws.util.EC2MetadataUtils: error
cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
      static: ap-northeast-2
    stack:
      auto: false

---
spring:
  config:
    activate:
      on-profile: dev
    import: 'aws-parameterstore:'
  r2dbc:
    url: ${r2dbc.url}
    username: ${r2dbc.username}
    password: ${r2dbc.password}
token:
  access-token-secret: ${jwt.secret}
  refresh-token-expired: 1209600
  access-token-expired: 1209600

aws:
  paramstore:
    enabled: true
    prefix: /
    profile-separator: _
    name: gateway
