name: master
on:
  push: #
    branches: [ 'master' ]
  workflow_dispatch:
    inputs:
      repository:
        description: 'master'
        required: true
      sync_only:
        description: 'sync only flag'
        required: false
    branch:

env:
  MODULE_ROOT_PATH: ./test_web_xdm # 해당 모듈의 루트
  MODULE_JAR: ./test_web_xdm/build/libs/test_web_xdm-0.0.1-SNAPSHOT.jar # 해당 모듈의 jar
  MODULE_DEPLOY_PATH: ./test_web_xdm/deploy # 해당 모듈의 deploy 디렉토리
  MODULE_DEPLOY_APPSPEC: ./test_web_xdm/deploy/appspec-test_web_xdm.yml # 해당 모듈의 appspec 파일
  AWS_REGION: ap-northeast-2 # aws 리전
  S3_BUCKET_NAME: test-awss3-vic # s3 버켓 이름
  AWS_CODE_DEPLOY_APP_NAME: test-server # aws code deploy 애플리케이션 이름
  AWS_CODE_DEPLOY_APP_GROUP_NAME: test-server-group # 애플리케이션 그룹 이름
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for root gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: create main boot jar
        run: ./gradlew bootJar -p $MODULE_ROOT_PATH

      - name: Copy Jar
        run: cp $MODULE_JAR deploy.jar

      - name: cp appspec file
        run: cp $MODULE_DEPLOY_APPSPEC appspec.yml

      - name: cp script files
        run: cp -r $MODULE_DEPLOY_PATH scripts

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip ./appspec.yml ./deploy.jar ./scripts
        shell: bash

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{env.AWS_REGION}}

      - name: upload to S3
        run: aws s3 cp --region $AWS_REGION ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME

      - name: send to aws code deploy
        run: aws deploy create-deployment --application-name $AWS_CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $AWS_CODE_DEPLOY_APP_GROUP_NAME --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip